// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvWRG9wIimZn6ct_ULw7rv7f58yqZc-WI',
    appId: '1:264682360658:ios:ef8e9d4524dde571e6348b',
    messagingSenderId: '264682360658',
    projectId: 'sfms-d63e9',
    storageBucket: 'sfms-d63e9.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu3vkxDZCg2MV6oGSkRMg6KVQ-y5whyhg',
    appId: '1:264682360658:web:c007b9ebe52faed0e6348b',
    messagingSenderId: '264682360658',
    projectId: 'sfms-d63e9',
    authDomain: 'sfms-d63e9.firebaseapp.com',
    storageBucket: 'sfms-d63e9.firebasestorage.app',
    measurementId: 'G-0B49GEJT2K',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvWRG9wIimZn6ct_ULw7rv7f58yqZc-WI',
    appId: '1:264682360658:ios:ef8e9d4524dde571e6348b',
    messagingSenderId: '264682360658',
    projectId: 'sfms-d63e9',
    storageBucket: 'sfms-d63e9.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLDeHB4-XC2CzCksUT-IavR7yPkciJcxA',
    appId: '1:264682360658:android:9edb0d34895259e0e6348b',
    messagingSenderId: '264682360658',
    projectId: 'sfms-d63e9',
    storageBucket: 'sfms-d63e9.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAu3vkxDZCg2MV6oGSkRMg6KVQ-y5whyhg',
    appId: '1:264682360658:web:6f5af921d7a538fce6348b',
    messagingSenderId: '264682360658',
    projectId: 'sfms-d63e9',
    authDomain: 'sfms-d63e9.firebaseapp.com',
    storageBucket: 'sfms-d63e9.firebasestorage.app',
    measurementId: 'G-WN0MFMTR7B',
  );
}
