<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Standard Laravel database-notifications table shape (normally
     * generated by `php artisan notifications:table` — hand-written here
     * since no PHP/Composer runtime is available in the dev sandbox that
     * wrote this migration). Backs the in-app notification center (every
     * notification is recorded here regardless of whether a push
     * actually reaches the device — see App\Notifications\Channels\FcmChannel)
     * for: matched drivers, CRM Admin on manual-pricing, company on
     * delivery-awaiting-confirmation, driver on balance/payout events,
     * account-approval changes, and new compliance reports.
     */
    public function up(): void
    {
        Schema::create('notifications', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->string('type');
            $table->morphs('notifiable');
            $table->text('data');
            $table->timestamp('read_at')->nullable();
            $table->timestamps();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('notifications');
    }
};
